### ISSUE TITLE
Do not comment on every PR that's included in a release

### ISSUE THREAD

**Issue by qwerty287** [woodpecker-ci/plugin-ready-release-go#2]
If we would use this plugin for woodpecker (or another project that might have hundreds of PRs in a release), you'd get a notification on github for every PR which is pretty annoying if you get >100 of them for already merged PRs.
My idea would be to change the original description of the PR to contain the message that this PR is included, possibly separated from the main content using `---`.

Example: https://github.com/woodpecker-ci/helm/pull/51#issuecomment-1675863120

**Comment by anbraten** [comment]
I get your point, however I really liked this feature from semantic-release which nicely notifies a user that his PR was finally released: https://github.com/renovatebot/renovate/issues/23574#issuecomment-1698078972

**Comment by anbraten** [comment]
I've added an option so we can disable it in large repos: https://github.com/woodpecker-ci/plugin-ready-release-go/commit/2531aa8057e9cc935c90a3d9e1070001bc114899
