### ISSUE TITLE
After releasing RC changelog still should contain all PRs

### ISSUE THREAD

**Issue by qwerty287** [woodpecker-ci/plugin-ready-release-go#52]
e.g. https://github.com/woodpecker-ci/woodpecker/pull/2805

**Comment by anbraten** [comment]
Good point. How would this be done best? It adds pre-releases with all changes in the description contained in that release. It adds the changes to the changelog for each pre-release and as soon as the full version with a version matching the pre-release versions (`2.0.0-rc.0`, `2.0.0-rc.1`, ... into `2.0.0`) gets released it removed the pre-release versions from the changelog and adds one combined full version or should it leave the pre-release versions untouched and just add a combined entry?

**Comment by anbraten** [comment]
Yeah, that sounds nice and will create a clean changelog as well. Will try to open a PR tonight to fix this.
