### ISSUE TITLE
on switch from RC to full release, respect all changes

### ISSUE THREAD

**Issue by 6543** [woodpecker-ci/plugin-ready-release-go#61]
atm only the canges between the last rc are tracked

see https://github.com/woodpecker-ci/woodpecker/pull/2805#discussion_r1399930224

**Comment by anbraten** [comment]
it shows `# First pre-release tag is: v2.0.0-rc.0 adding commits between v2.0.0-rc.0 and main` in the log so it has the correct boundaries now, but I guess 

```ts
unTaggedCommits = await git.log({
        from: firstRCTag, // v2.0.0-rc.0
        to: releaseBranch, // main
        symmetric: false,
      });
```

is missing to include the changes from `v2.0.0-rc.0`. Any ideas how I need to adjust the `git.log` call?
